export enum Notifications {
  Information,
  Warning,
  Error,
}

// const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';
// export type ERROR_NOTIFICATION = typeof ERROR_NOTIFICATION;

// const WARNING_NOTIFICATION = 'WARNING_NOTIFICATION';
// export type WARNING_NOTIFICATION = typeof WARNING_NOTIFICATION;

// const INFORMATION_NOTIFICATION = 'INFORMATION_NOTIFICATION';
// export type INFORMATION_NOTIFICATION = typeof INFORMATION_NOTIFICATION;

// export type Notifications = typeof ERROR_NOTIFICATION | typeof WARNING_NOTIFICATION | typeof INFORMATION_NOTIFICATION;
