language: node_js

node_js:
  - 'node'

script:
  - cd client && npm install && cd ..
  - cd client && npm run build && cd ..
  - cd client && npm test && cd ..
  - cd server && npm install && cd ..
  - cd server && npm run build && cd ..

branches:
  only:
  - master

cache:
  directories:
    - client/node_modules
    - server/node_modules

git:
  depth: 1