export const CREATE_GAME = 'CREATE_GAME';
export type CREATE_GAME = typeof CREATE_GAME;

export const INPUT_CHANGED = 'INPUT_CHANGED';
export type INPUT_CHANGED = typeof INPUT_CHANGED;

export const SET_GAME_NAME = 'SET_GAME_NAME';
export type SET_GAME_NAME = typeof SET_GAME_NAME;

export const SET_GAME_NUMBEROFPLAYERS = 'SET_GAME_NUMBEROFPLAYERS';
export type SET_GAME_NUMBEROFPLAYERS = typeof SET_GAME_NUMBEROFPLAYERS;

export const SET_GAME_USERID = 'SET_GAME_USERID';
export type SET_GAME_USERID = typeof SET_GAME_USERID;
