export const SUBSCRIBETO_GAME = 'SUBSCRIBETO_GAME';
export type SUBSCRIBETO_GAME = typeof SUBSCRIBETO_GAME;

export const SUBSCRIBEDTO_GAME = 'SUBSCRIBEDTO_GAME';
export type SUBSCRIBEDTO_GAME = typeof SUBSCRIBEDTO_GAME;

export const SUBSCRIBEDGAME_UPDATE = 'SUBSCRIBEDGAME_UPDATE';
export type SUBSCRIBEDGAME_UPDATE = typeof SUBSCRIBEDGAME_UPDATE;

