export const FETCH_GAME = 'FETCH_GAME';
export type FETCH_GAME = typeof FETCH_GAME;

export const FETCHED_GAME = 'FETCHED_GAME';
export type FETCHED_GAME = typeof FETCHED_GAME;

export const ADDPLAYERTO_GAME = 'ADDPLAYERTO_GAME';
export type ADDPLAYERTO_GAME = typeof ADDPLAYERTO_GAME;

export const ADDEDPLAYERTO_GAME = 'ADDEDPLAYERTO_GAME';
export type ADDEDPLAYERTO_GAME = typeof ADDEDPLAYERTO_GAME;

export const EDITEDPLAYER_NAME = 'EDITEDPLAYER_NAME';
export type EDITEDPLAYER_NAME = typeof EDITEDPLAYER_NAME;

export const EDITEDPLAYER_POINTS = 'EDITEDPLAYER_POINTS';
export type EDITEDPLAYER_POINTS = typeof EDITEDPLAYER_POINTS;

export const DELETEPLAYERFROM_GAME = 'DELETEPLAYERFROM_GAME';
export type DELETEPLAYERFROM_GAME = typeof DELETEPLAYERFROM_GAME;
